config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users
  resources :recipes do
    member do
      patch :update
      patch :toggle_public
    end
    resources :recipe_foods
  end
  resources :foods
  resources :public_recipes
  get 'general_shopping_list', to: 'general_shopping_list#index', as: 'general_shopping_list'
  get '/', to: 'users#index'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy

  validates :name, :measurement_unit, :price, :quantity, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user

  def user_name
    user.name
  end

  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods, dependent: :destroy

  def total_price
    total = 0
    recipe_foods.each do |rf|
      food = Food.find(rf.food_id)
      total += (rf.quantity * food.price)
    end
    total
  end

  def total_quantity
    qt = 0
    recipe_foods.each do |rf|
      qt += rf.quantity if rf.recipe_id == id
    end
    qt
  end

  validates :name, :preparation_time, :cooking_time, :description, presence: true
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  def recipe_id
    recipe.id
  end

  def total_price
    food.quantity * food.price
  end

  validates :quantity, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :foods
  has_many :recipes

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password, :name) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:email, :password, :current_password, :name)
    end
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = current_user.foods
  end

  def show; end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new params_provider
    @food.user = current_user

    if @food.save
      flash[:notice] = 'Food created succesfully'
      redirect_to foods_path
    else
      flash[:alert] = 'Error'
      render :new
    end
  end

  def destroy
    @food = Food.find(params[:id])
    if current_user == @food.user
      @food.destroy
      redirect_to recipes_path, notice: 'Food was successfully destroyed.'
    else
      redirect_to recipes_path, notice: 'You are not authorized to delete this food.'
    end
  end

  def params_provider
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/general_shopping_list_controller.rb
class GeneralShoppingListController < ApplicationController
  def index
    @user = current_user
    @recipes = Recipe.where(user_id: @user.id)
    @foods = Food.where(user_id: @user.id)
    @missing_foods = @foods - @recipes.flat_map(&:foods)
    @total_food_items = @missing_foods.map(&:name).uniq.count
    @total_price = 0
    @missing_foods.each do |food|
      @total_price += food.quantity.to_f * food.price.to_f
    end

    @total_price = BigDecimal(@total_price, 2)
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @recipes = Recipe.where(public: true).order(created_at: :desc)
    @users = User.all
    @recipe_foods = RecipeFood.all
  end

  def show; end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def index; end

  def new
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.new
    @recipe_food.recipe_id = params[:recipe_id]
    @foods = Food.all
  end

  def create
    @recipe_food = RecipeFood.new(recipe_food_params)
    @recipe_food.recipe_id = params[:recipe_id]

    if @recipe_food.save
      redirect_to recipe_path(params[:recipe_id]), notice: 'Food added to recipe.'
    else
      redirect_to recipe_recipe_foods_new_path(@recipe), alert: 'Unable to add food to recipe.'
    end
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:recipe_id, :food_id, :quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show destroy]

  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
    @foods = Food.all
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user

    if current_user.nil?
      redirect_to new_user_session_path, notice: 'You need to sign in or sign up before continuing.'
      return
    end

    if @recipe.save
      redirect_to recipes_path, notice: 'Recipe was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    if current_user == @recipe.user
      @recipe.destroy
      redirect_to recipes_path, notice: 'Recipe was successfully destroyed.'
    else
      redirect_to recipes_path, notice: 'You are not authorized to delete this recipe.'
    end
  end

  def update
    @recipe = Recipe.find(params[:id])
    @recipe.update(public: params[:public])
    redirect_to @recipe
  end

  def toggle_public
    @recipe = Recipe.find(params[:id])
    @recipe.update(public: !@recipe.public?)
    redirect_to @recipe
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/general_shopping_list_helper.rb
module GeneralShoppingListHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/foods/index.html.erb
<%= render 'shared/menu' %>

<div class='flex flex-col content-center items-center m-5 p-2'>

    <table class='w-3/6 mt-5 text-sm text-left text-gray-500 dark:text-gray-400'>
    <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">    
    <tr>
            <th scope="col" class="px-6 py-3">Food</th>
            <th scope="col" class="px-6 py-3">Measurement unit</th>
            <th scope="col" class="px-6 py-3">Unit price</th>
            <th scope="col" class="px-6 py-3">Quantity</th>
            <th scope="col" class="px-6 py-3">Actions</th>
        </tr>
        </thead>
        <% @foods.each do |food| %>
        <tr class="bg-white border-b dark:bg-gray-900 dark:border-gray-700">
            <td class="px-6 py-4"> <%= food.name %> </td>
            <td class="px-6 py-4"> <%= food.measurement_unit %> </td>
            <td class="px-6 py-4"> <%= food.price %> </td>
            <td class="px-6 py-4"> <%= food.quantity %> </td>
            <td class="px-6 py-4"> <%= button_to "Remove",
            food_path(food),
            method: :delete,
            class: "bg-white hover:bg-gray-100 text-gray-800 font-semibold py-1 px-2 border border-gray-400 rounded shadow" %> </td>
        </tr>
        <% end %>
    </table>
    
    <a href = <%= new_food_url %> >
        <button class="m-2 bg-white hover:bg-gray-100 text-gray-800 font-semibold py-1 px-2 border border-gray-400 rounded shadow">Add Food</button>
    </a>
</div>

app/views/foods/new.html.erb
<%= render 'shared/menu' %>

<div class='flex flex-col justify-center content-center items-center'>
    <%= form_with model: @food, url: foods_url, class: 'flex flex-col w-3/6' do |form| %>

    <div class='form-items'>
        <%= form.label :name, class: "block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" %></br>
        <%= form.text_field :name, class: "mt-1 border-2 border-black block w-full rounded-md shadow-sm focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
    </div>

    <div class='form-items'>
        <%= form.label :measurement_unit, class: "block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" %></br>
        <%= form.text_field :measurement_unit, class: "mt-1 border-2 border-black block w-full rounded-md shadow-sm focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
    </div>

    <div class='form-items'>
        <%= form.label :price, class: "block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" %></br>
        <%= form.text_field :price, class: "mt-1 border-2 border-black block w-full rounded-md shadow-sm focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
    </div>

    <div class='form-items'>
        <%= form.label :quantity, class: "block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" %></br>
        <%= form.text_field :quantity, class: "mt-1 border-2 border-black block w-full rounded-md shadow-sm focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
    </div>

    <div class="m-2 bg-white hover:bg-gray-100 text-gray-800 font-semibold py-1 px-2 border border-gray-400 rounded shadow" style="width: 70px;">
        <%= form.submit value="Submit" %>
    </div>
    <% end %>
</div>

app/views/general_shopping_list/index.html.erb
<%= render 'shared/menu' %>

<div class='flex flex-col content-center items-center m-5 p-2'>
<h1 class="text-4xl font-extrabold dark:text-white m-5">Shopping List</h1>

<% missing_foods = {} %>
<% total_quantity = 0 %>
<% total_price = 0 %>

<% current_user.recipes.includes(recipe_foods: :food).each do |recipe| %>
  <% recipe.recipe_foods.each do |recipe_food| %>
    <% food = recipe_food.food %>
    <% if missing_foods[food.id].nil? %>
      <% missing_foods[food.id] = food %>
      <% missing_foods[food.id][:quantity] = recipe_food.quantity %>
    <% else %>
      <% missing_foods[food.id][:quantity] += recipe_food.quantity %>
    <% end %>
  <% end %>
<% end %>

<% if missing_foods.any? %>
    <% missing_foods.each do |id, food| %>
      <% total_quantity += food.quantity - missing_foods[id][:quantity] %>
      <% total_price += (food.price * food.quantity) %>
    <% end %>
  </ul>
<% else %>
  <p>No missing food items found.</p>
<% end %>

<div class='flex w-5/6 justify-around my-4'>
<p>Amount of food items to buy: <%= missing_foods.count %></p>
<p>Total value of food needed: $<%= total_price %></p>
</div>

<table class='w-3/6 mt-5 text-sm text-left text-gray-500 dark:text-gray-400'>
<thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
<tr>
    <th scope="col" class="px-6 py-3">Food</th>
    <th scope="col" class="px-6 py-3">Quantity</th>
    <th scope="col" class="px-6 py-3">Price</th>
  </tr>
</thead>
  <% missing_foods.each do |id, food| %>
    <tr class="bg-white border-b dark:bg-gray-900 dark:border-gray-700">
      <td class="px-6 py-4"><%= food.name %></td>
      <td class="px-6 py-4"><%= food.quantity %> <%= food.measurement_unit %></td>
      <td class="px-6 py-4">$<%= food.price %></td>
    </tr>
  <% end %>
</table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipesApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %> 
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <% flash.each do |key, value| %>
      <% if key == "notice" %>
        <div class="alert alert-success flex flex-col content-center items-center" role="alert">
          <%= value %>
        </div>
      <% end %>
    <% end %>
  </body>
</html>

app/views/public_recipes/index.html.erb
<%= render 'shared/menu' %>
<div class="flex flex-col content-center items-center">
    <h1 class="text-4xl font-extrabold dark:text-white m-5">Public Recipes</h1>
        <% @recipes.each do |recipe| %>
            <div class="flex justify-between gap-20 my-8 w-5/6 h-32 border-2 border-black p-2">
            <div class="flex flex-col gap-4 p-2 w-1/6 font-semibold">
                <p> <%= recipe.name %> </p>
                <p>By: <%= recipe.user_name %>
            </div>

            <div class='flex flex-col gap-4 p-2 w-4/6 font-semibold'> 
                <p>Total food items: <%= recipe.total_quantity %> </p>
                <p>Total price: <%= recipe.total_price %>
            </div>
        </div>
        <% end %>
    </div>
</div>

app/views/recipe_foods/_recipe_food.html.erb
<li>
  <%= recipe_food.food.name %>
  <%= recipe_food.quantity %>
</li>

app/views/recipe_foods/index.html.erb
<%= render 'shared/menu' %>
<div>
    <div class="relative inline-flex self-center">
        <svg class="text-white bg-purple-700 absolute top-0 right-0 m-2 pointer-events-none p-2 rounded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="40px" height="40px" viewBox="0 0 38 22" version="1.1">
            <title>F09B337F-81F6-41AC-8924-EC55BA135736</title>
            <g id="ZahnhelferDE—Design" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                <g id="ZahnhelferDE–Icon&amp;Asset-Download" transform="translate(-539.000000, -199.000000)" fill="#ffffff" fill-rule="nonzero">
                    <g id="Icon-/-ArrowRight-Copy-2" transform="translate(538.000000, 183.521208)">
                        <polygon id="Path-Copy" transform="translate(20.000000, 18.384776) rotate(135.000000) translate(-20.000000, -18.384776) " points="33 5.38477631 33 31.3847763 29 31.3847763 28.999 9.38379168 7 9.38477631 7 5.38477631"/>
                    </g>
                </g>
            </g>
        </svg>
        <select class="text-2xl font-bold rounded border-2 border-purple-700 text-gray-600 h-14 w-60 pl-5 pr-10 bg-white hover:border-gray-400 focus:outline-none appearance-none">
          <% @foods.each do |food| %>    
            <option><%= food.name %></option>
          <% end %>
        </select>
    </div>
</div>

<%= form_with model: @food do |form| %>
  <%= form.select :name, [] %>
<% end %>

app/views/recipe_foods/new.html.erb
<%= render 'shared/menu' %>
<div class="flex flex-col gap-4 my-4 w-full items-center justify-items-center">
<% if @foods %>
  <% @foods.each do |food| %>
    <div class="grid justify-items-center grid-cols-2 w-5/6 m-2 p-2 bg-white rounded-lg shadow-lg w-3/4">
      <h3 class="text-lg font-medium mb-2"><%= food.name %></h3>
      <%= form_with(model: [@recipe, @recipe_food], url: recipe_recipe_foods_path(@recipe)) do |form| %>
        <%= form.hidden_field :food_id, value: food.id %>
        <%= form.hidden_field :quantity, value: food.quantity %>
        <%= form.submit "Add to recipe", class: "bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded cursor-pointer" %>
      <% end %>
    </div>
  <% end %>
<% end %>
</div>

app/views/recipes/_form.html.erb
<div class="flex justify-center">
<%= form_with(model: recipe, local: true) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, class: "block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" %>
    <%= form.text_field :name, class: "mt-1 border-2 border-black block w-full rounded-md shadow-sm focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
  </div>
  
  <div class="field">
    <%= form.label :description, class: "block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" %>
    <%= form.text_field :description, class: "mt-1 border-2 border-black block w-full rounded-md shadow-sm focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
  </div>

  <div class="field">
    <%= form.label :preparation_time, class: "block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" %>
    <%= form.number_field :preparation_time, class: "mt-1 border-2 border-black block w-full rounded-md shadow-sm focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
  </div>

  <div class="field">
    <%= form.label :cooking_time, class: "block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" %>
    <%= form.number_field :cooking_time, class: "mt-1 border-2 border-black block w-full rounded-md shadow-sm focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
  </div>

  <div class="field">
    <%= form.label :public, class: "block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" %>
    <%= form.check_box :public %>
  </div>

  <div class="bg-white hover:bg-gray-100 flex text-gray-800 font-semibold py-1 px-2 border border-gray-400 rounded shadow" style="width: 65%;">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/recipes/_recipe.html.erb
<% if recipe.user == current_user %>
<div class="flex gap-20 my-8 w-5/6 h-32 border-2 border-black p-2">
<div class="flex flex-col gap-7 pt-2 w-1/6">
  <%= link_to recipe.name, recipe_path(recipe) %>
  <div class="py-2">
    <%= button_to "Remove",
                  recipe_path(recipe),
                  method: :delete,
                  class: "bg-white hover:bg-gray-100 text-gray-800 font-semibold py-1 px-2 border border-gray-400 rounded shadow" %>
  
  </div>
  </div>
  <div class="w-full p-2 text-ellipsis overflow-hidden">
  <%= recipe.description %>
  </div>
</div>
<% end %>

app/views/recipes/index.html.erb
<main class="flex flex-col content-center items-center">
<%= render 'shared/menu' %>
  <div class="header m-2">
    <%= link_to "New recipe",
                new_recipe_path,
                class: "bg-white hover:bg-gray-100 text-gray-800 font-semibold py-1 px-2 border border-gray-400 rounded shadow" %>
  </div>

  <%= render @recipes %>
</main>

app/views/recipes/new.html.erb
<main class="flex flex-col justify-center content-center items-center">
<%= render 'shared/menu' %>
  <div class="header">
    <h1 class="text-4xl font-extrabold dark:text-white m-5">New recipe</h1>
  </div>

  <%= render "form", recipe: @recipe %>
  <div class="m-2">
  <%= link_to sanitize("&larr; Back to recipes"), recipes_path %>
  </div>
</main>

app/views/recipes/show.html.erb
<main class="flex flex-col content-center items-center">
<%= render 'shared/menu' %>
  <div class="header">
    <h1 class="text-4xl font-extrabold dark:text-white m-5"><%= @recipe.name %></h1>  
  </div>

<div class="flex w-5/6 justify-between">
  <div class="flex flex-col gap-5 font-semibold">
    <p>Preparation time: <%= @recipe.preparation_time %> minutes</p>
    <p>Cooking time: <%= @recipe.cooking_time %> minutes</p>
    <p><%= @recipe.description %></p>
  </div>
  <% if @recipe.user == current_user %>
    <%= form_for @recipe, url: toggle_public_recipe_path(@recipe), method: :patch do |f| %>
    <label class="relative inline-flex items-center mr-5">
      <%= f.check_box :public, class: "sr-only peer", checked: @recipe.public %>
      <div class="w-11 h-6 bg-gray-200 rounded-full peer dark:bg-gray-700 peer-focus:ring-4 peer-focus:ring-green-300 dark:peer-focus:ring-green-800 peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-0.5 after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all dark:border-gray-600 peer-checked:bg-green-600"></div>
      <%= f.submit "Public", class: "cursor-pointer" %>
    </label>
    <% end %> 
  <% end %>  
  </div>  
  <% if @recipe.user == current_user %>
    <a href = <%= new_recipe_recipe_food_path(@recipe.id) %> class="flex self-end mr-20">
      <button class='bg-white hover:bg-gray-100 text-gray-800 font-semibold py-1 px-2 border border-gray-400 rounded shadow'>Add Ingredient</button>
    </a>
  <% end %>

<hr class="w-4/6 rounded-sm h-1 my-6 bg-gray-500" />

<table class='w-3/6 mt-5 text-sm text-left text-gray-500 dark:text-gray-400'>
  <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
    <tr>
      <th scope="col" class="px-6 py-3">Name</th>
      <th scope="col" class="px-6 py-3">Quantity</th>
      <th scope="col" class="px-6 py-3">Value</th>
      <th scope="col" class="px-6 py-3">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @recipe.recipe_foods.includes(:recipe).each do |recipe_food| %>
      <tr class="bg-white border-b dark:bg-gray-900 dark:border-gray-700">
        <td class="px-6 py-4"><%= recipe_food.food.name %></td>
        <td class="px-6 py-4"><%= recipe_food.quantity %></td>
        <td class="px-6 py-4"><%= recipe_food.food.price %></td>
        <td class="px-6 py-4">
          <p>Edit</p>
          <p>Delete</p>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

</main>

app/views/shared/_menu.html.erb
  <div class="flex items-center justify-center content-center w-full" id="navbar-sticky">
    <ul class="flex gap-4 w-full p-4 justify-around content-center font-medium border border-gray-100 bg-gray-50">
      <li>
        <a href= <%= foods_url %> class="block  text-gray-900">Foods</a>
      </li>
      <li>
        <a href= <%= recipes_url %> class="block text-gray-900">Recipes</a>
      </li>
      <li>
        <a href= <%= public_recipes_url %> class="block text-gray-900">Public Recipes</a>
      </li>
      <li>
        <a href= <%= general_shopping_list_url %> class="block text-gray-900">GSL</a>
      </li>
    </ul>
  </div>